"""
A program that demonstrates templates knowledge graph generation from log files
as well as knowledge graph completion for anomaly detection
"""

import cProfile
import io
import pstats
import os
import shutil
import yaml

import numpy as np

from anomaly_detection.kg_generation import ait_dataset
from anomaly_detection.kg_generation.kg_generation import generate_kg
from anomaly_detection.kg_completion.kg_completion import kg_completion

def clean_preprocessed_files(raw_data_dir: str, dataset_name: str) -> None:
    """
    Remove preprocessed data files generated by a previous run of the program
    """
    kgg_path = os.path.join(os.path.dirname(__file__), "anomaly_detection", "kg_generation")
    kgc_path = os.path.join(os.path.dirname(__file__), "anomaly_detection", "kg_completion")
    shutil.rmtree(os.path.join(raw_data_dir, "train"), ignore_errors=True)
    shutil.rmtree(os.path.join(raw_data_dir, "test"), ignore_errors=True)
    shutil.rmtree(os.path.join(kgg_path, "templates", dataset_name), ignore_errors=True)

    metadata_file = os.path.join(kgc_path, "datasets", dataset_name, "metadata.json")
    test_file = os.path.join(kgc_path, "datasets", dataset_name, "test.txt")
    train_file = os.path.join(kgc_path, "datasets", dataset_name, "train.txt")
    val_file = os.path.join(kgc_path, "datasets", dataset_name, "valid.txt")
    if os.path.isfile(metadata_file):
        os.remove(metadata_file)
    if os.path.isfile(test_file):
        os.remove(test_file)
    if os.path.isfile(train_file):
        os.remove(train_file)
    if os.path.isfile(val_file):
        os.remove(val_file)

def main():
    """
    The demo code
    """
    np.random.seed(1234)
    ait_raw_data_dir = os.path.join(os.path.dirname(__file__), "data", "AIT")

    clean = True
    if clean:
        clean_preprocessed_files(ait_raw_data_dir, "AIT")

    exclude_errors = True
    ait_dataset.extract_dataset(ait_raw_data_dir, exclude_errors)

    pr = cProfile.Profile()
    pr.enable()
    generate_kg(ait_raw_data_dir, "AIT")
    pr.disable()

    s = io.StringIO()
    sortby = pstats.SortKey.TIME
    ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
    ps.print_stats()

    profile_path = os.path.join("results", "profile.txt")
    with open (profile_path, "w+", encoding="utf-8") as f:
        f.write(s.getvalue())

    cfg_path = "config/ait.yaml"
    cfg: dict = {}
    with open(cfg_path, "r", encoding="utf-8") as cfg_file:
        cfg = yaml.safe_load(cfg_file)
    kg_completion(cfg)

if __name__ == "__main__":
    main()
